on: [push]

jobs:
  create_shipa_app:
    runs-on: ubuntu-latest
    name: Create shipa app
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create shipa app
        uses: ./ # Uses an action in the root directory
        id: create-app
        env:
          SHIPA_TOKEN: ${{ secrets.SHIPA_TOKEN }}
          SHIPA_HOST: ${{ secrets.SHIPA_HOST }}
        with:
          file-path: './apps/app.yml'
